import { withBase } from "../../../utils/assetPath";

const url = (path) => withBase(`comp/${path.replace(/^\/+/, "")}`);

export default [
  {
    name: "base",
    data: {},
    items: [
      { name: "topChairModel", source: url("assets/models/topChair.glb"), type: "model" },
      { name: "rubiksCube", source: url("assets/models/Rubik.glb") },
      { name: "skyTexture", source: url("assets/textures/skyTexture.ktx2"), type: "texture" },
      { name: "perlin", source: url("assets/textures/perlin.png"), type: "texture" },
      { name: "baked1", source: url("assets/textures/baked1.ktx2"), type: "texture" },
      { name: "baked2", source: url("assets/textures/baked2.ktx2"), type: "texture" },
      { name: "baked3", source: url("assets/textures/baked3.ktx2"), type: "texture" },
      { name: "_roomModel", source: url("assets/models/room.glb") },
      { name: "_roomModel2", source: url("assets/models/room2.glb") },
      { name: "_roomModel3", source: url("assets/models/room3.glb") },
      { name: "whiteboard", source: url("assets/models/whiteboard.glb") },
      { name: "leftMonitor", source: url("assets/models/leftMonitor.glb") },
      { name: "rightMonitor", source: url("assets/models/rightMonitor.glb") },
      { name: "arcadeMachine", source: url("assets/models/arcadeMachine.glb") },
      { name: "linkedin", source: url("assets/models/linkedin.glb") },
      { name: "github", source: url("assets/models/github.glb") },
      { name: "itchio", source: url("assets/models/itchio.glb") },
      {
        name: "cubeTexture",
        source: [
          url("assets/environmentMaps/nx.jpg"),
          url("assets/environmentMaps/ny.jpg"),
          url("assets/environmentMaps/nz.jpg"),
          url("assets/environmentMaps/px.jpg"),
          url("assets/environmentMaps/py.jpg"),
          url("assets/environmentMaps/pz.jpg"),
        ],
        type: "cubeTexture",
      },
      { name: "markerOpen", source: url("assets/sounds/marker-open.mp3") },
      { name: "eraser", source: url("assets/sounds/eraser.mp3") },
      { name: "confetti", source: url("assets/sounds/confetti.mp3") },
      { name: "partyblower", source: url("assets/sounds/partyblower.mp3") },
      { name: "footstep01", source: url("assets/sounds/footstep01.ogg") },
      { name: "footstep02", source: url("assets/sounds/footstep02.ogg") },
      { name: "footstep03", source: url("assets/sounds/footstep03.ogg") },
      { name: "mouseclick", source: url("assets/sounds/mouseclick.ogg") },
      { name: "mouserelease", source: url("assets/sounds/mouserelease.ogg") },
      { name: "rubik_1", source: url("assets/sounds/rubik_1.mp3") },
      { name: "rubik_2", source: url("assets/sounds/rubik_2.mp3") },
      { name: "rubik_3", source: url("assets/sounds/rubik_3.mp3") },
      { name: "start", source: url("assets/sounds/start.mp3") },
      { name: "vase_break", source: url("assets/sounds/vase_break.mp3") },
      { name: "door", source: url("assets/sounds/door.mp3") },
      { name: "trophy", source: url("assets/sounds/trophy.mp3") },
      { name: "trophy_platinum", source: url("assets/sounds/trophy_platinum.mp3") },
      { name: "floral", source: url("assets/sounds/floral.mp3") },
      { name: "hit", source: url("assets/sounds/hit.ogg") },
      { name: "tetris", source: url("assets/sounds/tetris.ogg") },
      { name: "die", source: url("assets/sounds/die.ogg") },
      { name: "whoosh", source: url("assets/sounds/whoosh.mp3") },
      { name: "select1", source: url("assets/sounds/select1.ogg") },
      { name: "select2", source: url("assets/sounds/select2.ogg") },
      { name: "screnshot", source: url("assets/social/screenshot.png") },
    ],
  },
];
