import { lazy } from 'react';
import { stripBase } from '../utils/assetPath';

function lazyTheme(loader, exportName) {
  return lazy(() => loader().then((module) => ({ default: module[exportName] })));
}

function assertUniqueThemeField(field) {
  const seen = new Map();

  for (const theme of PORTFOLIO_THEMES) {
    const value = theme[field];
    if (!value) continue;

    if (seen.has(value)) {
      throw new Error(`Duplicate theme ${field} "${value}" in ${seen.get(value)} and ${theme.id}`);
    }

    seen.set(value, theme.id);
  }
}


export const PORTFOLIO_THEMES = [
  {
    id: 'ansub-minimal',
    slug: 'minimal',
    name: 'Minimal',
    description: 'Clean single-page layout powered by CV.yaml. Features a timeline experience view, projects section, and contact info.',
    source: 'https://ansub.com',
    Component: lazyTheme(() => import('./AnsubMinimal/AnsubMinimalTheme'), 'AnsubMinimalTheme'),
  },
  {
    id: 'boehs',
    slug: 'indie-garden',
    name: 'Indie Garden',
    description: 'Warm paper layout with serif typography, left-rule cards, a playful status line, and footer navigation inspired by boehs.org.',
    source: 'https://boehs.org',
    Component: lazyTheme(() => import('./Boehs/BoehsTheme'), 'BoehsTheme'),
  },
  {
    id: 'brutalist',
    slug: 'brutalist',
    name: 'Brutalist',
    description: 'No-frills, lightweight design. Just content, system fonts, and zero bullshit.',
    source: null,
    Component: lazyTheme(() => import('./Brutalist/BrutalistTheme'), 'BrutalistTheme'),
  },
  {
    id: 'chiang-v4',
    slug: 'developer-dark',
    name: 'Developer Dark',
    description: 'Dark navy portfolio with green accents. Full-page sections with numbered headings.',
    source: 'https://v4.brittanychiang.com',
    Component: lazyTheme(() => import('./ChiangV4/ChiangV4Theme'), 'ChiangV4Theme'),
  },
  {
    id: 'chiang-current',
    slug: 'spotlight',
    name: 'Spotlight',
    description: 'Modern two-column layout with slate colors and teal accents. Sticky navigation with scroll-aware highlighting.',
    source: 'https://brittanychiang.com',
    Component: lazyTheme(() => import('./ChiangCurrent/ChiangCurrentTheme'), 'ChiangCurrentTheme'),
  },
  {
    id: 'nick-computer',
    slug: 'creative-dark',
    name: 'Creative Dark',
    description: 'Bold dark theme with Rammetto One display font. Horizontal project cards and clean experience list.',
    source: 'https://nick.computer',
    Component: lazyTheme(() => import('./NickComputer/NickComputerTheme'), 'NickComputerTheme'),
  },
  {
    id: 'brian-lovin',
    slug: 'designer',
    name: 'Designer',
    description: 'Clean minimal portfolio with centered content, monospace dates, and elegant project listings.',
    source: 'https://brianlovin.com',
    Component: lazyTheme(() => import('./BrianLovin/BrianLovinTheme'), 'BrianLovinTheme'),
  },
  {
    id: 'josh-bradley',
    slug: 'editorial',
    name: 'Editorial',
    description: 'Two-column layout with italic navigation, justified text, and leader-dot lists. Warm cream background with serif accents.',
    source: 'https://joshbradley.me',
    Component: lazyTheme(() => import('./JoshBradley/JoshBradleyTheme'), 'JoshBradleyTheme'),
  },
  {
    id: 'hendo',
    slug: 'hendo',
    name: 'Hendo',
    description: 'Clean minimal design with scramble text animation on hover. Light/dark mode toggle, centered content, and simple navigation.',
    source: 'https://hendo.dev',
    Component: lazyTheme(() => import('./Hendo/HendoTheme'), 'HendoTheme'),
  },
  {
    id: 'pi',
    slug: 'research-lab',
    name: 'Research Lab',
    description: 'Monospace timeline layout with featured cards and box shadows. Cream background, serif logo, and vertical timeline with square dots.',
    source: 'https://www.andrewheiss.com',
    Component: lazyTheme(() => import('./Pi/PiTheme'), 'PiTheme'),
  },
  {
    id: 'chizi',
    slug: 'modern-blue',
    name: 'Modern Blue',
    description: 'Clean minimalist design with blue accents. Features a live clock, project cards grid, and smooth hover animations.',
    source: 'https://chizi.me',
    Component: lazyTheme(() => import('./Chizi/ChiziTheme'), 'ChiziTheme'),
  },
  {
    id: 'gerhard',
    slug: 'plain-text',
    name: 'Plain Text',
    description: 'Ultra-minimal design with system fonts, 60ch width, and automatic dark/light mode. Subtle gray underlines and muted section labels.',
    source: 'https://gerhard.io',
    Component: lazyTheme(() => import('./Gerhard/GerhardTheme'), 'GerhardTheme'),
  },
  {
    id: 'alana-goyal',
    slug: 'notes',
    name: 'Notes',
    description: 'Notes-style layout with emoji icons, golden accent color, and dark mode default. Clean SF Pro typography with lowercase aesthetic.',
    source: 'https://alanagoyal.com',
    Component: lazyTheme(() => import('./AlanaGoyal/AlanaGoyalTheme'), 'AlanaGoyalTheme'),
  },
  {
    id: 'aysar',
    slug: 'founder-badge',
    name: 'Founder Badge',
    description: 'Clean white portfolio with dark glass floating nav, Manrope typography, rounded project cards, and source-matched contact form.',
    source: 'https://www.aysark.com',
    Component: lazyTheme(() => import('./Aysar/AysarTheme'), 'AysarTheme'),
  },
  {
    id: 'amirmxt',
    slug: 'builder',
    name: 'Builder',
    description: 'Clean professional layout with card-based projects and section dividers. Inter font, subtle hover effects, and live footer clock.',
    source: 'https://amirmxt.com',
    Component: lazyTheme(() => import('./Amirmxt/AmirmxtTheme'), 'AmirmxtTheme'),
  },
  {
    id: 'felix-dorner',
    slug: 'timeline',
    name: 'Timeline',
    description: 'Clean professional design with timeline layout, monospace dates, and indigo accent links. Inter font with uppercase section labels.',
    source: 'https://felixdorner.com',
    Component: lazyTheme(() => import('./FelixDorner/FelixDornerTheme'), 'FelixDornerTheme'),
  },
  {
    id: 'terminal',
    slug: 'terminal',
    name: 'Terminal',
    description: 'Hacker-style black terminal with Geist Mono font, ALL CAPS text, blinking cursor, and animated link underlines.',
    source: 'https://ragojose.com',
    Component: lazyTheme(() => import('./Terminal/TerminalTheme'), 'TerminalTheme'),
  },
  {
    id: 'terminal-master',
    slug: 'terminal-master',
    name: 'Terminal Master',
    description: 'Interactive green-screen shell adapted from a standalone jQuery terminal portfolio, rebuilt as a CV-driven command interface.',
    source: 'https://marwanebourdim.github.io/terminal/',
    Component: lazyTheme(() => import('./TerminalMaster/TerminalMasterTheme'), 'TerminalMasterTheme'),
  },
  {
    id: 'jamie-pates',
    slug: 'sandbox-save',
    name: 'Sandbox Save',
    description: 'PS1-inspired interface with FF7-style panels, tabbed file views, and a game UI treatment driven by CV.yaml data.',
    source: 'https://www.jamiepates.com',
    Component: lazyTheme(() => import('./JamiePates/JamiePatesTheme'), 'JamiePatesTheme'),
  },
  {
    id: 'stammy',
    slug: 'stammy',
    name: 'Stammy',
    description: 'Dark olive theme with left icon sidebar, serif typography, and table-style work history.',
    source: 'https://paulstamatiou.com',
    Component: lazyTheme(() => import('./Stammy/StammyTheme'), 'StammyTheme'),
  },
  {
    id: 'stefan-fisk',
    slug: 'business-card',
    name: 'Business Card',
    description: 'Ultra-minimal centered contact page with classic serif typography and simple hover-underlined links.',
    source: 'https://stefanfisk.com',
    Component: lazyTheme(() => import('./StefanFisk/StefanFiskTheme'), 'StefanFiskTheme'),
  },
  {
    id: 'stefan-zweifel',
    slug: 'developer',
    name: 'Developer',
    description: 'Clean white portfolio with pride gradient bar, system fonts, underlined links, and tabular date formatting.',
    source: 'https://stefanzweifel.dev',
    Component: lazyTheme(() => import('./StefanZweifel/StefanZweifelTheme'), 'StefanZweifelTheme'),
  },
  {
    id: 'dmythro',
    slug: 'two-column',
    name: 'Two Column',
    description: 'Modern two-column layout with sticky photo card, accordion sections, timeline with chip dates, and gradient social buttons. Dark mode support.',
    source: 'https://dmythro.com',
    Component: lazyTheme(() => import('./Dmythro/DmythroTheme'), 'DmythroTheme'),
  },
  {
    id: 'dtc',
    slug: 'splash',
    name: 'Splash',
    description: 'Full-screen hero splash with profile picture, colorful project cards, and alternating timeline. Dark theme with Roboto typography.',
    source: 'https://dtc.dev',
    Component: lazyTheme(() => import('./DTC/DTCTheme'), 'DTCTheme'),
  },
  {
    id: 'kubre',
    slug: 'notebook',
    name: 'Notebook',
    description: 'Monospace terminal aesthetic with glitch-style header, yellow accent hovers, and notebook paper dots.',
    source: 'https://kubre.in',
    Component: lazyTheme(() => import('./Kubre/KubreTheme'), 'KubreTheme'),
  },
  {
    id: 'paco',
    slug: 'paco',
    name: 'Paco',
    description: 'Minimalist grayscale portfolio with staggered animations, three-column layout, and indigo accent.',
    source: 'https://paco.me',
    Component: lazyTheme(() => import('./Paco/PacoTheme'), 'PacoTheme'),
  },
  {
    id: 'p5aholic',
    slug: 'framed',
    name: 'Framed',
    description: 'Artistic portfolio with border frame, mix-blend-mode difference, left navigation with dot indicators, and right-aligned projects. Sans/Mono toggle.',
    source: 'https://p5aholic.me',
    Component: lazyTheme(() => import('./P5aholic/P5aholicTheme'), 'P5aholicTheme'),
  },
  {
    id: 'rinkitadhana',
    slug: 'dashed',
    name: 'Dashed',
    description: 'Clean portfolio with dashed border separators, dot grid header, social pills, and two-column project grid. Geist-inspired typography.',
    source: 'https://rinkitadhana.com',
    Component: lazyTheme(() => import('./Rinkitadhana/RinkitadhanaTheme'), 'RinkitadhanaTheme'),
  },
  {
    id: 'u11g',
    slug: 'mainframe',
    name: 'Mainframe',
    description: 'Brutalist dashboard with zinc surfaces, monospace typography, topic cards with colored accents, and grid-based project layout.',
    source: 'https://u11g.com',
    Component: lazyTheme(() => import('./U11g/U11gTheme'), 'U11gTheme'),
  },
  {
    id: 'shubham',
    slug: 'imml',
    name: 'IMML',
    description: 'Minimal page-based portfolio with hash navigation, blockquote work entries, project tables, and dotted link underlines.',
    source: 'https://shubhwym.me',
    Component: lazyTheme(() => import('./Shubham/ShubhamTheme'), 'ShubhamTheme'),
  },
  {
    id: 'palmes',
    slug: '3d-duck',
    name: '3D Duck',
    description: 'Dark portfolio with scroll-synchronized 3D duck animation, cyan gradients, and comprehensive CV display.',
    source: 'https://palmes.dev',
    Component: lazyTheme(() => import('./Palmes/PalmesTheme'), 'PalmesTheme'),
  },
  {
    id: 'abstract-systems',
    slug: 'abstract',
    name: 'Abstract Systems',
    description: 'Minimal blue-gray portfolio with floating pill nav, staggered fade-in animations, dotted section dividers, and monospace accents.',
    source: 'https://www.abstract.systems',
    Component: lazyTheme(() => import('./AbstractSystems/AbstractSystemsTheme'), 'AbstractSystemsTheme'),
  },
  {
    id: 'rashad-wiki',
    slug: 'wikipedia',
    name: 'Wikipedia',
    description: 'Wikipedia-inspired portfolio with serif headings, infobox sidebar, blue links, and encyclopedia-style biography sections.',
    source: 'https://rashad.wiki',
    Component: lazyTheme(() => import('./RashadWiki/RashadWikiTheme'), 'RashadWikiTheme'),
  },
  {
    id: 'alicia-page',
    slug: 'lime-grid',
    name: 'Lime Grid',
    description: 'Minimalist portfolio with lime green accents, 12-column grid layout, ASCII art header, animated link underlines, and dark/light mode.',
    source: 'https://alicias.page',
    Component: lazyTheme(() => import('./AliciaPage/AliciaPageTheme'), 'AliciaPageTheme'),
  },
  {
    id: 'ed-henderson',
    slug: 'monotype',
    name: 'Monotype',
    description: 'Minimalist monospace portfolio with Roboto Mono, 600px content width, dropdown nav with dividers, bullet-point sections, and copy-to-clipboard email.',
    source: 'https://ed-henderson.com',
    Component: lazyTheme(() => import('./EdHenderson/EdHendersonTheme'), 'EdHendersonTheme'),
  },
  {
    id: 'henrylang',
    slug: 'retro-os',
    name: 'Retro OS',
    description: 'WebGL desktop portfolio with draggable windows, browser-style markdown pages, paint app, and CV-backed text files.',
    source: 'https://henrylang.net',
    Component: lazyTheme(() => import('./HenryLang/HenryLangTheme'), 'HenryLangTheme'),
  },
  {
    id: 'liam-matteson',
    slug: 'liam-cv',
    name: 'Liam CV',
    description: 'Editorial white portfolio with muted green-gray typography, oversized serif statement, underlined nav, and image-led project cards.',
    source: 'https://www.liam.cv',
    Component: lazyTheme(() => import('./LiamMatteson/LiamMattesonTheme'), 'LiamMattesonTheme'),
  },
  {
    id: 'kelly-chong',
    slug: 'paper-notes',
    name: 'Paper Notes',
    description: 'Soft paper-texture portfolio with a sticky pixel-nav, editorial serif headings, footer clock, and section blocks adapted from kellychong.ca.',
    source: 'https://kellychong.ca',
    Component: lazyTheme(() => import('./KellyChong/KellyChongTheme'), 'KellyChongTheme'),
  },
  {
    id: 'rodney-v2',
    slug: 'paper-pixel',
    name: 'Paper Pixel',
    description: 'Paper-toned monospace portfolio with pixel headings, blue accent heatmap, fixed nav, live clock, and comprehensive CV sections inspired by v2.rodney.lol.',
    source: 'https://v2.rodney.lol',
    Component: lazyTheme(() => import('./RodneyV2/RodneyV2Theme'), 'RodneyV2Theme'),
  },
  {
    id: 'sinister-suns',
    slug: 'moonrest',
    name: 'Moonrest',
    description: 'Dark fantasy resume theme with ivy corners, ornamental borders, parchment-toned type, and a tavern-inspired information architecture remade from the Sinister Suns site.',
    source: 'https://sinistersuns.neocities.org',
    Component: lazyTheme(() => import('./SinisterSuns/SinisterSunsTheme'), 'SinisterSunsTheme'),
  },
  {
    id: 'saint-angels',
    slug: 'with-teeth',
    name: 'With Teeth',
    description: 'Minimal retro panel layout with a left nav, bordered content cards, and a rotating wireframe header adapted from saint-angels.github.io.',
    source: 'https://saint-angels.github.io',
    Component: lazyTheme(() => import('./SaintAngels/SaintAngelsTheme'), 'SaintAngelsTheme'),
  },
  {
    id: 'ruth-zhao',
    slug: 'ruth-zhao',
    name: 'Ruth Zhao',
    description: 'Soft editorial portfolio with IBM Plex Mono details, orange feature cards, airy panels, and a research-forward layout adapted from ruth-zhao.com.',
    source: 'https://www.ruth-zhao.com',
    Component: lazyTheme(() => import('./RuthZhao/RuthZhaoTheme'), 'RuthZhaoTheme'),
  },
  {
    id: 'taha-hossain',
    slug: 'daybreak',
    name: 'Daybreak',
    description: 'Warm beige two-column portfolio with colored border lines, EB Garamond serif body, monospace technical details, and numbered resume items inspired by tahahossain.com.',
    source: 'https://tahahossain.com',
    Component: lazyTheme(() => import('./TahaHossain/TahaHossainTheme'), 'TahaHossainTheme'),
  },
  {
    id: 'bao-to',
    slug: 'design-engineer',
    name: 'Design Engineer',
    description: 'Warm cream portfolio with glitch text hero, uppercase tab nav, monospace accents, and staggered project cards inspired by baothiento.com.',
    source: 'https://www.baothiento.com',
    Component: lazyTheme(() => import('./BaoTo/BaoToTheme'), 'BaoToTheme'),
  },
  {
    id: 'pcv',
    slug: 'ascii-flame',
    name: 'ASCII Flame',
    description: 'Monospace split-screen portfolio with 7 cyclable color themes, interactive ASCII doom flame animation, and uppercase vertical rhythm inspired by p.cv.',
    source: 'https://p.cv',
    Component: lazyTheme(() => import('./PCV/PCVTheme'), 'PCVTheme'),
  },
  {
    id: 'wallenart-tui',
    slug: 'terminal-ui',
    name: 'Terminal UI',
    description: 'Lazygit-inspired split-pane TUI with sidebar navigation, vim keybindings, item counters, and monospace Fira Mono typography.',
    source: 'https://wallenart.dev',
    Component: lazyTheme(() => import('./WallenartTUI/WallenartTUITheme'), 'WallenartTUITheme'),
  },
  {
    id: 'nim',
    slug: 'nim',
    name: 'Nim',
    description: 'Minimalist portfolio with staggered fade-in animations, spotlight hover cards, social pills, and zinc color palette inspired by nim-fawn.vercel.app.',
    source: 'https://nim-fawn.vercel.app',
    Component: lazyTheme(() => import('./Nim/NimTheme'), 'NimTheme'),
  },
  {
    id: 'retro-computer',
    slug: 'retro-computer',
    name: 'Retro Computer',
    description: 'Interactive CRT terminal with virtual filesystem, retro Commodore PET styling, scan-line effects, and warm beige portfolio content inspired by edh.dev.',
    source: 'https://edh.dev',
    Component: lazyTheme(() => import('./RetroComputer/RetroComputerTheme'), 'RetroComputerTheme'),
  },
  {
    id: 'vscode-portfolio',
    slug: 'vscode',
    name: 'VS Code',
    description: 'IDE-themed portfolio with Atom One Dark colors, tab navigation, left activity bar, status bar, and code-file section names.',
    source: 'https://github.com/caglarturali/vscode-portfolio',
    Component: lazyTheme(() => import('./VSCodePortfolio/VSCodePortfolioTheme'), 'VSCodePortfolioTheme'),
  },
  {
    id: 'sharpeye08',
    slug: 'italic-mono',
    name: 'Italic Mono',
    description: 'Pitch-black monospace portfolio with italic Georgia section titles, short divider rule, uppercase entry tags, and a light/dark toggle inspired by sharpeye08.github.io.',
    source: 'https://sharpeye08.github.io',
    Component: lazyTheme(() => import('./SharpEye08/SharpEye08Theme'), 'SharpEye08Theme'),
  },
  {
    id: 'matt-rothenberg',
    slug: 'editorial-prose',
    name: 'Editorial Prose',
    description: 'Narrative single-column layout with oversized Fraunces serif paragraphs, mono "I ___" eyebrows, inline employment pills, and editorial underlines inspired by mattrothenberg.com.',
    source: 'https://mattrothenberg.com',
    Component: lazyTheme(() => import('./MattRothenberg/MattRothenbergTheme'), 'MattRothenbergTheme'),
  },
  {
    id: 'joost-damhuis',
    slug: 'framer-mono',
    name: 'Framer Mono',
    description: 'Dark single-viewport landing with an oversized lowercase name, live clock widget, teal accents, and a now-playing card inspired by joost.design.',
    source: 'https://joost.design',
    Component: lazyTheme(() => import('./JoostDamhuis/JoostDamhuisTheme'), 'JoostDamhuisTheme'),
  },
  {
    id: 'chester-how',
    slug: 'digital-garden',
    name: 'Digital Garden',
    description: 'A quiet masonry digital garden with Fraunces serif display type, pill nav, and color-tagged cards — inspired by chester.how.',
    source: 'https://chester.how',
    Component: lazyTheme(() => import('./ChesterHow/ChesterHowTheme'), 'ChesterHowTheme'),
  },
  {
    id: 'jacob-leech',
    slug: 'digital-craftsman',
    name: 'Digital Craftsman',
    description: 'Warm camel-and-brown editorial layout with Cormorant Garamond body, Bluu Titling display type, boxed drop caps, "Fig." figure captions, and bordered graphic panels — inspired by jacobleech.com.',
    source: 'https://jacobleech.com',
    Component: lazyTheme(() => import('./JacobLeech/JacobLeechTheme'), 'JacobLeechTheme'),
  },
  {
    id: 'talk-to-dasha',
    slug: 'pastel-cards',
    name: 'Pastel Cards',
    description: 'Cream background with pastel-colored section cards, floating pill headings, and rotated white mini-cards. Inter Tight typography and a playful, approachable mood inspired by talktodasha.com.',
    source: 'https://www.talktodasha.com',
    Component: lazyTheme(() => import('./TalkToDasha/TalkToDashaTheme'), 'TalkToDashaTheme'),
  },
  {
    id: 'floperillat-chat',
    slug: 'resume-chat',
    name: 'Resume Chat',
    description: 'Fake iMessage-style resume chat with blue and gray bubbles, suggested prompts, typed name intro, and heuristic auto-replies based on CV.yaml. Inspired by floperillat.com.',
    source: 'https://floperillat.com',
    Component: lazyTheme(() => import('./FloperillatChat/FloperillatChatTheme'), 'FloperillatChatTheme'),
  },
  {
    id: 'faiz-raeim',
    slug: 'faiz-raeim',
    name: 'Brutal Blocks',
    description: 'Dark brutalist portfolio with block-based sections, Figtree display typography, animated accents, and CV-backed project and contact areas.',
    source: 'https://faizraeim.com',
    Component: lazyTheme(() => import('./FaizRaeim/FaizRaeimTheme'), 'FaizRaeimTheme'),
  },
  {
    id: 'kaachow',
    slug: 'threw-it-away',
    name: 'Threw It Away',
    description: 'Playful single-viewport hero with an oversized serif headline and a draggable physics-driven trash can full of crumpled papers, plus a custom "find me here instead" cursor — inspired by kaachow.xyz.',
    source: 'https://www.kaachow.xyz',
    Component: lazyTheme(() => import('./Kaachow/KaachowTheme'), 'KaachowTheme'),
  },
  {
    id: 'vemula',
    slug: 'card-stack',
    name: 'Card Stack',
    description: 'Editorial serif headline with inline avatar and sparkle, paired with a bottom-fixed row of overlapping gradient cards that lift and rotate on hover. Inspired by vemula.me.',
    source: 'https://vemula.me',
    Component: lazyTheme(() => import('./Vemula/VemulaTheme'), 'VemulaTheme'),
  },
  {
    id: 'ben-issen',
    slug: 'sketchpad',
    name: 'Sketchpad',
    description: 'Two floating dark cards (avatar + tabbed project list, and big-name bio with newsletter) on top of an interactive drawing canvas you can doodle on with three colors and a variable brush. Inspired by benissen.com.',
    source: 'https://benissen.com',
    Component: lazyTheme(() => import('./BenIssen/BenIssenTheme'), 'BenIssenTheme'),
  },
  {
    id: 'hacked-jekyll',
    slug: 'hacked',
    name: 'Hacked',
    description: 'Terminal-inspired JSON portfolio that renders your CV as a formatted JSON object with monospace Hack font, green-on-dark styling, and a typewriter animation. Based on piazzai/hacked-jekyll.',
    source: 'https://piazzai.github.io/hacked-jekyll/',
    Component: lazyTheme(() => import('./HackedJekyll/HackedJekyllTheme'), 'HackedJekyllTheme'),
  },
  {
    id: 'comp',
    slug: 'comp-room',
    name: 'Comp Room',
    description: 'WebGL desktop diorama with an arcade machine, twin monitors, whiteboard and Rubik\'s cube — orbit around the room and click props to dive into CV-driven screens. Adapted from joanramosrefusta.com.',
    source: 'https://joanramosrefusta.com',
    Component: lazyTheme(() => import('./Comp/CompTheme'), 'CompTheme'),
  },
  {
    id: 'aiden-bai',
    slug: 'aiden-bai',
    name: 'Aiden Bai',
    description: 'Narrow text-only portfolio with stone neutrals, serif heading, understated underlined links, shimmer emphasis, and expandable lore inspired by aidenybai.com without the image strip.',
    source: 'https://www.aidenybai.com',
    // Shell-level opt-ins for this theme (distinct from cv.features, which is
    // user data from CV.yaml). reactGrab gates the Aiden Bai visual-edit
    // helper behind VITE_ENABLE_REACT_GRAB.
    shellFeatures: { reactGrab: true },
    Component: lazyTheme(() => import('./AidenBai/AidenBaiTheme'), 'AidenBaiTheme'),
  },
  {
    id: 'lochie-axon',
    slug: 'markdown-fun',
    name: 'Markdown Fun',
    description: 'Tiny markdown-styled portfolio with default serif typography, dash lists, source favicon, bracketed links, and a deliberately goofy Comic Sans sign-off inspired by lochieaxon.com.',
    source: 'https://lochieaxon.com',
    Component: lazyTheme(() => import('./LochieAxon/LochieAxonTheme'), 'LochieAxonTheme'),
  },
  {
    id: 'sharon-zheng',
    slug: 'cobalt-fold',
    name: 'Cobalt Fold',
    description: 'Cobalt blue folding portfolio with oversized uppercase name, square bullets, underlined external links, and print-poster energy inspired by sharonzheng.com.',
    source: 'https://sharonzheng.com',
    Component: lazyTheme(() => import('./SharonZheng/SharonZhengTheme'), 'SharonZhengTheme'),
  },
  {
    id: 'sebastian-berns',
    slug: 'research-designer',
    name: 'Research Designer',
    description: 'Warm gray editorial portfolio with Work Sans-style body text, oversized inline serif phrases, two-column navigation, and vivid accent colors inspired by sebastianberns.com.',
    source: 'https://sebastianberns.com',
    Component: lazyTheme(() => import('./SebastianBerns/SebastianBernsTheme'), 'SebastianBernsTheme'),
  },
  {
    id: 'norman-ponte',
    slug: 'orbital-notes',
    name: 'Orbital Notes',
    description: 'Black space portfolio with shader-twinkled stars, orbiting GLB artifacts, Radar display type, sticky translucent navigation, and CV-backed content panels inspired by normanponte.io.',
    source: 'https://normanponte.io',
    Component: lazyTheme(() => import('./NormanPonte/NormanPonteTheme'), 'NormanPonteTheme'),
  },
  {
    id: 'noah-finer',
    slug: 'shader-playground',
    name: 'Shader Playground',
    description: 'Playful olive WebGL portfolio with noisy fragment shaders, distorted title textures, blocky project cards, Basteleur display type, and captured media inspired by noahfiner.com.',
    source: 'https://noahfiner.com',
    Component: lazyTheme(() => import('./NoahFiner/NoahFinerTheme'), 'NoahFinerTheme'),
  },
  {
    id: 'hey-this-is-chris',
    slug: 'hey-this-is-chris',
    name: 'Hey This Is Chris',
    description: 'Compact blue-gray portfolio with an animated canvas grid, hover-filled squares, dark mode switch, marquee feed, bordered panels, icon-led entries, and CV-backed resume/project/contact views inspired by heythisischris.com.',
    source: 'https://heythisischris.com',
    Component: lazyTheme(() => import('./HeyThisIsChris/HeyThisIsChrisTheme'), 'HeyThisIsChrisTheme'),
  },
  {
    id: 'daniel-petho',
    slug: 'scramble',
    name: 'Scramble',
    description: 'Off-white editorial portfolio with right-aligned label columns, oversized clean sans type, and signature scramble-in-on-load plus scramble-on-hover text effects inspired by danielpetho.com.',
    source: 'https://www.danielpetho.com',
    Component: lazyTheme(() => import('./DanielPetho/DanielPethoTheme'), 'DanielPethoTheme'),
  },
  {
    id: 'vibe-coded',
    slug: 'vibe-coded',
    name: 'Vibe Coded',
    description: 'WebGPU ASCII-shader scene reproduced on canvas: a metaball fluid field of colorful glyph islands behind a glowing yellow box window with CONTACT/PROJECTS tabs, a "$ " prompt, a Tweakpane-style Shader Controls panel, and a /dice easter egg, faithful to vibe-coded.com.',
    source: 'https://vibe-coded.com',
    Component: lazyTheme(() => import('./VibeCoded/VibeCodedTheme'), 'VibeCodedTheme'),
  },
  {
    id: 'qtzx',
    slug: 'what-if',
    name: 'What If',
    description: 'Monochrome dark/light portfolio with a curl-noise GPGPU particle hero behind a closing frame, typewriter greetings, a GSAP photo card-swap, a "what if?" ASCII panel, SDF-bordered media, and a spinning target cursor — faithfully rebuilt from qtzx.dev.',
    source: 'https://qtzx.dev',
    Component: lazyTheme(() => import('./Qtzx/QtzxTheme'), 'QtzxTheme'),
  },
  {
    id: 'terishim',
    slug: 'in-orbit',
    name: 'In Orbit',
    description: 'Silvery instrument-panel portfolio with DM Mono micro-labels, a faded serif monogram, a drifting starfield, a floating glass device mockup, and work rows with animated double-arrows inspired by terishim.com.',
    source: 'https://www.terishim.com',
    Component: lazyTheme(() => import('./Terishim/TerishimTheme'), 'TerishimTheme'),
  },
  {
    id: 'benson-yan',
    slug: 'liquid-rose',
    name: 'Liquid Rose',
    description: 'Minimal near-black portfolio with a cursor-reactive rose-and-peach fluid canvas, Lora serif name, diamond-bullet credentials, and ↳-arrow project and experience lists inspired by 1800benson.ca.',
    source: 'https://www.1800benson.ca',
    Component: lazyTheme(() => import('./BensonYan/BensonYanTheme'), 'BensonYanTheme'),
  },
  {
    id: 'win-tongtawee',
    slug: 'mono-card',
    name: 'Mono Card',
    description: 'Pitch-dark Geist Mono single column capped at 480px with a hover-swap avatar, lowercase aesthetic, social glyphs, quiet year-labelled experience and education lists, and a project list that floats a preview card by the cursor — inspired by wintongtawee.dev.',
    source: 'https://www.wintongtawee.dev',
    Component: lazyTheme(() => import('./WinTongtawee/WinTongtaweeTheme'), 'WinTongtaweeTheme'),
  },
  {
    id: 'donchuru',
    slug: 'quiet-intro',
    name: 'Quiet Intro',
    description: 'A single quiet paragraph of Inter prose on a near-white ground — a "hi, i\'m ___" greeting that folds work, writing, and contact into plain sentences with understated underlined links, inspired by donchuru.github.io.',
    source: 'https://donchuru.github.io',
    Component: lazyTheme(() => import('./Donchuru/DonchuruTheme'), 'DonchuruTheme'),
  },
  {
    id: 'cp-domina',
    slug: 'serif-hello',
    name: 'Serif Hello',
    description: 'Ultra-minimal classic-serif page: a bold "Hi" and one flowing paragraph that folds email, GitHub, LinkedIn, CV, and publications into inline blue underlined links, inspired by cpdomina.net.',
    source: 'https://www.cpdomina.net',
    Component: lazyTheme(() => import('./CpDomina/CpDominaTheme'), 'CpDominaTheme'),
  },
  {
    id: 'sanjay-engineering',
    slug: 'sky-mono',
    name: 'Sky Mono',
    description: 'Calm sky-blue gradient set in Geist Mono with a rotated name rail, blocky Departure Mono section headers, and quiet two-column project, writing, and experience rows, inspired by sanjay.engineering.',
    source: 'https://sanjay.engineering',
    Component: lazyTheme(() => import('./SanjayEngineering/SanjayEngineeringTheme'), 'SanjayEngineeringTheme'),
  },
  {
    id: 'jen-liu',
    slug: 'dashed-news',
    name: 'Dashed News',
    description: 'A web-1.0 academic homepage in Times serif — a blue flower-wrapped name, a bulleted nav, and a dotted-magenta "recent news" box of dated headlines, inspired by jenliujenliu.com.',
    source: 'https://jenliujenliu.com',
    Component: lazyTheme(() => import('./JenLiu/JenLiuTheme'), 'JenLiuTheme'),
  },
  {
    id: 'kieran-computer',
    slug: 'built-things',
    name: 'Built Things',
    description: 'A hushed single-column serif page — a square portrait tile, a bold serif name, an arrow-bulleted list of things built, and a compact ↗ links row — inspired by kieran.computer.',
    source: 'https://www.kieran.computer',
    Component: lazyTheme(() => import('./KieranComputer/KieranComputerTheme'), 'KieranComputerTheme'),
  },
  {
    id: 'aidan-nelson',
    slug: 'hello-welcome',
    name: 'Hello & Welcome',
    description: 'A minimal editorial serif reader on warm white — a big bold greeting, generous bio paragraphs, an old-fashioned monospace email, and a rule-separated project list with colored letter tiles, inspired by aidanjnelson.com.',
    source: 'https://www.aidanjnelson.com',
    Component: lazyTheme(() => import('./AidanNelson/AidanNelsonTheme'), 'AidanNelsonTheme'),
  },
  {
    id: 'kielljoy',
    slug: 'neocities',
    name: 'Blinking Serif',
    description: 'Minimalist neocities landing with a bold lowercase serif name, a hard-blinking text cursor, and a bright color-dotted bullet nav above quiet serif CV sections, inspired by kielljoy.neocities.org.',
    source: 'https://kielljoy.neocities.org',
    Component: lazyTheme(() => import('./Kielljoy/KielljoyTheme'), 'KielljoyTheme'),
  },
  {
    id: 'spencer-kinney',
    slug: 'iridescent',
    name: 'Iridescent',
    description: 'Centered near-black mono column with a huge holographic-filled name, an underlined "building … at" tagline, and hairline-ruled previously/links sections, inspired by spencerkinney.dev.',
    source: 'https://www.spencerkinney.dev',
    Component: lazyTheme(() => import('./SpencerKinney/SpencerKinneyTheme'), 'SpencerKinneyTheme'),
  },
  {
    id: 'yongseok',
    slug: 'digital-rain',
    name: 'Digital Rain',
    description: 'A quiet zinc blog shell with a language switch, a ticking clock, and blog/about links above a dark hero of matrix-style ASCII rain and a glowing monospace wordmark, inspired by yongseok.me.',
    source: 'https://yongseok.me',
    Component: lazyTheme(() => import('./Yongseok/YongseokTheme'), 'YongseokTheme'),
  },
  {
    id: 'sadale',
    slug: 'retro-web',
    name: 'Retro Web',
    description: 'A gleeful early-web homepage on a cream-to-yellow gradient with a bubbly orange WordArt headline, friendly bulleted sections, and a row of 88×31 badges, inspired by sadale.net.',
    source: 'https://sadale.net',
    Component: lazyTheme(() => import('./Sadale/SadaleTheme'), 'SadaleTheme'),
  },
  {
    id: 'sylvain-paris',
    slug: 'academic-classic',
    name: 'Academic Classic',
    description: 'A nostalgic early-2000s faculty homepage with a centered tab bar, a pale blue-gray content panel, and beveled section headers over justified prose, inspired by an MIT CSAIL faculty homepage.',
    source: 'https://people.csail.mit.edu/sparis/',
    Component: lazyTheme(() => import('./SylvainParis/SylvainParisTheme'), 'SylvainParisTheme'),
  },
  {
    id: 'pranav-ramesh',
    slug: 'shell-prompt',
    name: 'Shell Prompt',
    description: 'A clean interactive terminal on near-black — type help, ls, cat about.txt, projects, or open github to explore a CV through a working command prompt with history, inspired by pranavramesh.com.',
    source: 'https://www.pranavramesh.com',
    Component: lazyTheme(() => import('./PranavRamesh/PranavRameshTheme'), 'PranavRameshTheme'),
  },
  {
    id: 'donghoon',
    slug: 'scholar',
    name: 'Scholar',
    description: 'A clean academic homepage with a sticky top nav, an inline-linked bio, and selected-publication and project cards, inspired by donghoon.io.',
    source: 'https://donghoon.io',
    Component: lazyTheme(() => import('./Donghoon/DonghoonTheme'), 'DonghoonTheme'),
  },
  {
    id: 'adam-watters',
    slug: 'maker-log',
    name: 'Maker Log',
    description: 'A clean, light maker portfolio with hairline borders and monospace labels — a warm intro, a Projects grid of aspect-video cards, and a dated Essays index, inspired by adamwatters.co.',
    source: 'https://adamwatters.co',
    Component: lazyTheme(() => import('./AdamWatters/AdamWattersTheme'), 'AdamWattersTheme'),
  },
  {
    id: 'vlad-savruk',
    slug: 'coverflow',
    name: 'Coverflow',
    description: 'A whitespace-heavy designer portfolio with a restrained masthead and a 3D coverflow carousel of work cards you can drag, swipe, and autoplay, inspired by vladsavruk.com.',
    source: 'https://vladsavruk.com',
    Component: lazyTheme(() => import('./VladSavruk/VladSavrukTheme'), 'VladSavrukTheme'),
  },
  {
    id: 'tyler-lorenzen',
    slug: 'now-playing',
    name: 'Now Playing',
    description: 'A music-streaming-inspired dark portfolio with a playlist of work experience, skill chips, project cards, and a now-playing footer bar, inspired by tylerlorenzen.tech.',
    source: 'https://tylerlorenzen.tech',
    Component: lazyTheme(() => import('./TylerLorenzen/TylerLorenzenTheme'), 'TylerLorenzenTheme'),
  },
];

if (import.meta.env?.DEV) {
  assertUniqueThemeField('id');
  assertUniqueThemeField('slug');
}

export const THEME_INDEX_BY_ID = new Map(PORTFOLIO_THEMES.map((theme, index) => [theme.id, index]));
export const THEME_BY_ID = new Map(PORTFOLIO_THEMES.map((theme) => [theme.id, theme]));
export const THEME_BY_SLUG = new Map(PORTFOLIO_THEMES.map((theme) => [theme.slug, theme]));

export function getPortfolioTheme(themeId) {
  return THEME_BY_ID.get(themeId) || PORTFOLIO_THEMES[0];
}

export function getThemeBySlug(slug) {
  return THEME_BY_SLUG.get(slug);
}

export function getThemeIdFromPath(pathname) {
  const stripped = stripBase(pathname);
  const slug = stripped.replace(/^\/+|\/+$/g, '').toLowerCase();
  if (!slug) return null;
  const theme = getThemeBySlug(slug);
  return theme ? theme.id : null;
}
